name: Postman Test

on:
  push:
    branches:
      - main

jobs:
  postman-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: newman run ${{ github.workspace }}/postman/collections/LaraCommerce API.json -d 1 -n 100
