name: CICD
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Chrome
        - uses: logikal-io/install-chrome@v1
          with:
           version: 123
        - name: Checkout
          uses: actions/checkout@v4
        - uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install
          run: npm install
        - name: Test
          run: npm run wdio cicd.wdio.conf.js
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs
